### ISSUE TITLE
 Core dump observed in netconf-client implemented using libnetconf2 when try to create two netconf sessions in different ssh channels in same ssh session and peer disconnects

### ISSUE THREAD

**Issue by shishirpandey29** [CESNET/libnetconf2#134]
Hi, 

I am using libnetconf2 for implementing netconf client and requirement is to create 2 netconf sessions in different ssh channels in same ssh.
Some times , I have observed a core dump. From logs and code analysis , I found below scenario that caused problem: 

1)	Application(netconf client, single threaded application ) creates a first netconf session with netconf server successfully and when tries to creates 2nd netconf session in different ssh channel in same ssh,
it fails because of Error :  “Opening an SSH channel failed (Socket error: Connection reset by peer)”.

Function calls for 2nd netconf session in same ssh:
``` 
Refer COMMENT 
func  nc_connect_ssh_channel()
   {
        ………….
1760  if (open_netconf_channel(new_session, NC_TRANSPORT_TIMEOUT) != 1) {  
                                                    // COMMENT:  -1 return here , and
                                                     fail goto statement called , STEP-1
1761         goto fail;
      }
      …………..
      …………….
1797 fail:
1798     nc_session_free(new_session, NULL); //COMMENT:  1st netconf session is not added in
             2nd netconf session 's next session list and nc_session_free called , STEP-2 
1799     return NULL;
}

func nc_session_free()
{
   …….
     //COMMENT: Multisession = 0,                                    multisession is zero 
      //COMMENT: session->ti.libssh.next = NULL;            no other netconf session in same ssh

764   ssh_free(session->ti.libssh.session);  //COMMENT: delete ssh session  shared 
                                                 with 1st netconf session   
}
```
2)	Now application(netconf client) calls nc_session_free for deleting 1st netconf session(RUNNING  netconf session) .
  ```
REFER COMMENT 
func nc_session_free()   {
       …….
      //  COMMENT : Multisession = 0,                                     multisession is zero
     //  COMMENT : session->ti.libssh.next =   NULL;            no other netconf session in   same ssh  
     ....      
760    sock = ssh_get_fd(session->ti.libssh.session);   // COMMENT : tries to access socket of
                      ssh session ,but this ssh session is already deleted during freeing
                   2nd netconf session and core dumps occurs.
......
}
 ```
This problems occurs when 2nd netconf session is failed in same ssh session before line number 1777 in nc_connect_ssh_channel() function as 1st netconf session is not appended in 2nd netconf session 's  next netconf session list and vise versa.

LOG: 
 ```
lnc2_print_clb()| nc ERROR: Opening an SSH channel failed (Socket error: Connection reset by peer).
lnc2_print_clb()| nc ERROR: nc_write_msg_io: failed to IO lock a session (Invalid argument).
nc2_print_clb()| nc ERROR: nc_read_msg_poll_io: failed to IO lock a session (Invalid argument).
lnc2_print_clb()| nc ERROR: Session 3: failed to receive a reply to <close-session>.
 ```
BACKTRACE:
```
 (gdb) bt
#0  0x00007fcf6c081eab in ssh_socket_get_fd_in (s=0x0)
    at libssh/libssh-0.7.5/src/socket.c:508
#1  0x00007fcf6c07eb99 in ssh_get_fd (session=0x21a6320)
    at libssh/libssh-0.7.5/src/session.c:538
#2  0x00007fcf6be1d1e2 in nc_session_free (session=0x21a81a0, data_free=0x0)
    at libnetconf2-0.11-r1/src/session.c:703

```

**Comment by michalvasko** [comment]
Hi,
it could work now, will you please try it? Thanks.

Regards,
Michal

**Comment by shishirpandey29** [comment]
thanks for fix, I will apply the fix and will share result
