### ISSUE TITLE
netopeer2-server segfaults on `get` RPC

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libnetconf2#31]
Hi, it seems that the recent commit which fixes handlig of decimal64 list keys actually works. Here's how a ``get`` from the CLI ends up:

```
Thread 6 "netopeer2-serve" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb4afeb40 (LWP 1078)]
0xb7668b60 in resolve_partial_json_data_nodeid (nodeid=0xb6514c20 "/czechlight-roadm-v2:roadm/configuration/channel[center-frequency='195.3']/center-frequency", 
    llist_value=0xb4afe05c "195.3", '0' <repeats 12 times>, "1136868377216160297393798828125", '0' <repeats 152 times>..., start=0x30303030, options=1, 
    parsed=0xb4afdf9c) at /home/jkt/work/prog/buildroot/out-epia-geode/build/libyang-custom/src/resolve.c:2230
2230    /home/jkt/work/prog/buildroot/out-epia-geode/build/libyang-custom/src/resolve.c: No such file or directory.
(gdb) bt
#0  0xb7668b60 in resolve_partial_json_data_nodeid (nodeid=0xb6514c20 "/czechlight-roadm-v2:roadm/configuration/channel[center-frequency='195.3']/center-frequency", 
    llist_value=0xb4afe05c "195.3", '0' <repeats 12 times>, "1136868377216160297393798828125", '0' <repeats 152 times>..., start=0x30303030, options=1, 
    parsed=0xb4afdf9c) at /home/jkt/work/prog/buildroot/out-epia-geode/build/libyang-custom/src/resolve.c:2230
#1  0xb76d234e in lyd_new_path (data_tree=0x30303030, ctx=0x88c0420, 
    path=0xb6514c20 "/czechlight-roadm-v2:roadm/configuration/channel[center-frequency='195.3']/center-frequency", value=0xb4afe05c, 
    value_type=LYD_ANYDATA_CONSTSTRING, options=1) at /home/jkt/work/prog/buildroot/out-epia-geode/build/libyang-custom/src/tree_data.c:1229
#2  0x08057951 in opget_build_subtree_from_sysrepo (ds=0x892d320, root=0xb4afe110, subtree_xpath=0xb6503520 "/czechlight-roadm-v2:roadm")
    at /home/jkt/work/prog/buildroot/out-epia-geode/build/netopeer2-server-custom/server/op_get_config.c:62
#3  0x30303030 in ?? ()
#4  0x30303030 in ?? ()
#5  0x30303030 in ?? ()
#6  0x30303030 in ?? ()
#7  0x30303030 in ?? ()
#8  0x30303030 in ?? ()
#9  0x30303030 in ?? ()
#10 0x30303030 in ?? ()
#11 0x30303030 in ?? ()
#12 0x30303030 in ?? ()
#13 0x30303030 in ?? ()
#14 0x30303030 in ?? ()
#15 0x30303030 in ?? ()
#16 0x30303030 in ?? ()
#17 0x30303030 in ?? ()
#18 0x30303030 in ?? ()
#19 0x30303030 in ?? ()
#20 0x30303030 in ?? ()
#21 0x30303030 in ?? ()
#22 0x30303030 in ?? ()
#23 0x30303030 in ?? ()
#24 0x30303030 in ?? ()
#25 0x30303030 in ?? ()
#26 0x30303030 in ?? ()
#27 0x30303030 in ?? ()
#28 0x00000000 in ?? ()
```

A major part of the stack trace looks like garbage.

This is with freshly rebuild libyang/sysrepo/libnetconf2/netopeer2 from devel branches.

**Comment by jktjkt** [comment]
Sorry, wrong project :).
