### ISSUE TITLE
src/session_client.c:1535:49: runtime error: member access within address 0x7ffde54bac80 with insufficient space for an object of type 'struct sockaddr_in'

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libnetconf2#413]
After updating libnetconf2 from 9bca73d6349b1196acebc14c30d8cfadbc99b0df to 0b15664621a8eba22e0577a21738f22cf330f1f7, the test suite started crashing when run under ASAN+UBSAN, clang 15. It looks like 7b1c4c2 is the culprit:
```
10/13 Test #12: test_client_ssh ..................***Failed    1.10 sec
[==========] Running 16 test(s).
[ RUN      ] test_nc_client_ssh_setting_auth_pref
[       OK ] test_nc_client_ssh_setting_auth_pref
[ RUN      ] test_nc_client_ssh_setting_auth_hostkey_check_clb
[       OK ] test_nc_client_ssh_setting_auth_hostkey_check_clb
[ RUN      ] test_nc_client_ssh_setting_auth_password_clb
[       OK ] test_nc_client_ssh_setting_auth_password_clb
[ RUN      ] test_nc_client_ssh_setting_auth_interactive_clb
[       OK ] test_nc_client_ssh_setting_auth_interactive_clb
[ RUN      ] test_nc_client_ssh_setting_auth_privkey_passphrase_clb
[       OK ] test_nc_client_ssh_setting_auth_privkey_passphrase_clb
[ RUN      ] test_nc_client_ssh_adding_keypair
[ERR]: _nc_client_ssh_get_keypair: invalid argument (idx).
[ERR]: SSH key pair already set.
[ERR]: _nc_client_ssh_del_keypair: invalid argument (idx).
[       OK ] test_nc_client_ssh_adding_keypair
[ RUN      ] test_nc_client_ssh_setting_username
[       OK ] test_nc_client_ssh_setting_username
[ RUN      ] test_nc_connect_ssh_interactive_succesfull
CzechLight/dependencies/libnetconf2/src/session_client.c:1535:49: runtime error: member access within address 0x7ffde54bac80 with insufficient space for an object of type 'struct sockaddr_in'
0x7ffde54bac80: note: pointer points here
 00 00 00 00  90 02 00 00 60 60 00 00  19 00 00 00 00 00 00 00  33 00 00 00 00 00 00 00  80 06 19 2a
              ^
    #0 0x535734 in nc_saddr2str CzechLight/dependencies/libnetconf2/src/session_client.c:1535:49
    #1 0x5345a5 in sock_connect CzechLight/dependencies/libnetconf2/src/session_client.c:1574:13
    #2 0x533e21 in nc_sock_connect CzechLight/dependencies/libnetconf2/src/session_client.c:1692:20
    #3 0x5702ae in nc_connect_ssh CzechLight/dependencies/libnetconf2/src/session_client_ssh.c:1695:12
    #4 0x597236 in test_nc_connect_ssh_interactive_succesfull CzechLight/dependencies/libnetconf2/tests/client/test_client_ssh.c:540:15
    #5 0x7f062c692cb0  (/lib64/libcmocka.so.0+0x5cb0)
    #6 0x7f062c69338a in _cmocka_run_group_tests (/lib64/libcmocka.so.0+0x638a)
    #7 0x59627c in main CzechLight/dependencies/libnetconf2/tests/client/test_client_ssh.c:828:12
    #8 0x7f062afceb74 in __libc_start_main /usr/src/debug/glibc-2.33/csu/../csu/libc-start.c:332:16
    #9 0x4265ad in _start (/home/ci/build/libnetconf2/tests/test_client_ssh+0x4265ad)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior CzechLight/dependencies/libnetconf2/src/session_client.c:1535:49 in
```

**Comment by michalvasko** [comment]
Took me a moment, quite a serious typo. fixed.
